let recipes = [
    {
        "id": "0",
        "name": "Air Fryer Oreos",
        "category": "foreign",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2021/01/air-fryer-oreos-0958w.jpg",
        "favorited_amount": "189",
        description: 'Air fryer oreos are a little trip to the state fair, in the middle of winter. We could all use a bit of sweet, melty, gooey deliciousness, am I right? Crisp and fluffy deep fried crescent roll outsides with melty oreo frosting and chocolate cookies…I am dead.',
    },
    {
        "id": "1",
        "name": "Steak.",
        "category": "foreign",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2021/02/how-to-cook-steak-1061w.jpg",
        "favorited_amount": "154",
        description: '<i1>Steak</i1> is one of the easiest and most impressive things you can make. With a little bit of knowledge, pizzazz, and finesse, you can make steakhouse chef quality steaks right at home. If you’re already a steak-pro, you probably don’t need to read any further, but if you’re not that experienced at cooking steak and a little bit nervous, don’t be, it’s super easy!',
    },
    {
        "id": "2",
        "name": "Gà chiên mắm, mật ong",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2020/06/air-fryer-korean-fried-chicken-3701w-2.jpg",
        "favorited_amount": "237",
        description: 'Thịt gà là thực phẩm nhiều thịt nạc và ít mỡ, chứa nhiều protein. Rất nhiều món ăn ngon từ thịt gà bởi vì thịt gà không chỉ cung cấp nhiều dinh dưỡng mà còn giúp các bộ phận trong cơ thể như thận, gan, thần kinh hoạt động ổn định. Vì vậy hãy nhanh vào bếp thực ngay món <i>Gà chiên nước mắm mật ong</i> để thay đổi khẩu vị cho gia đình mà vẫn giữ được nguồn dinh dưỡng cần thiết.',
    },
    {
        "id": "3",
        "name": "Takoyaki Recipe",
        "category": "asia",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2012/07/takoyaki-recipe-4792w.jpg",
        "favorited_amount": "42",
        description: 'Takoyaki literally translated means octopus fried, but takoyaki isn’t just fried octopus – it’s a tiny, piping hot ball of batter filled with green onions, ginger, crispy tempura bits and octopus. It’s crisp, it’s gooey, it’s delicious.',
    },
    {
        "id": "4",
        "name": "TikTok Hot Chocolate Bombs",
        "category": "foreign",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2020/10/hot-chocolate-bombs-7604w-2.jpg",
        "favorited_amount": "207",
        description: 'It’s super cute and fun and you can make SO many flavor variations! They sell hot chocolate bombs/hot chocolate balls at the store, but around here I haven’t seen any so I decided to make my own. You can too!',
    },
    {
        "id": "5",
        "name": "Chinese Steamed Fish Recipe",
        "category": "asia",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2012/06/steamedfish-8.jpg",
        "favorited_amount": "125",
        description: 'Buying fresh fish might be a little daunting but most Asian grocery stores with a live tank will scale and gut your fish for you. As with all seafood fresh really is best, but if you don’t want to go with a whole fish, this recipe works just as well with any thick cut white fish filets.<br>If you’ve never had Chinese style steamed fish you should give it a go. Light, refreshing and oh-so simple, the flavour of the fish is clean, fresh and heightened by the ginger and green onions.',
    },
    {
        "id": "6",
        "name": "Vietnamese Caramelized Pork Belly Pasta",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2015/01/pork-belly-spaghetti-7wa1.jpg",
        "favorited_amount": "218",
        description: 'Pork belly: without a doubt, it’s a love it or hate it thing and I’m defiantly on the love it side. I have lots of friends that won’t touch the stuff. They think it’s incredibly unhealthy because of all the layers of fat. I get where they’re coming from, but pork belly (when it’s done right) is SO delicious. The people who don’t like belly are the people who don’t like bacon and to me, no bacon equals no life.',
    },
    {
        "id": "7",
        "name": "Bun Rieu: Vietnamese Tomato and Crab Noodle Soup",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2021/01/bun-rieu-recipe-0824w-2.jpg",
        "favorited_amount": "117",
        description: 'What is life without amazing noodle soups? And if you’re talking about amazing, bun rieu is up there with the greats.<br> In terms of Vietnamese noodle soups, Bun rieu is not as well known as pho or bun bo hue, but it’s a hidden gem maybe only you’ll know about among your friends: a time tested combination of al dente rice noodles, flavorful seafood and tomato soup, and intensely delicious and really pretty toppings. Think of it like a Vietnamese bouillabaisse.',
    },
    {
        "id": "8",
        "name": "Bibibap",
        "category": "asia",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2012/03/realbibimbap-153.jpg",
        "favorited_amount": "176",
        description: '<i1>Bibimbap</i1> hay còn được biết tới cái tên Cơm Trộn Hàn Quốc ở Việt Nam ta.Đây có thể nói là một món ăn làm nên tên tuổi của ẩm thực xứ sở kim chi, bởi vì dù một người không biết nhiều về nơi đây chắc chắn cũng đã từng nghe hay thưởng thức món ăn vô cùng hấp dẫn này',
    },
    {
        "id": "9",
        "name": "Phở xào giòn",
        "category": "viet",
        "img": "https://i.ytimg.com/vi/BXYsWrPVZfQ/maxresdefault.jpg",
        "favorited_amount": "241",
        description: 'Nếu cảm thấy món phở xào thông thường đã hơi nhàm chán thì bạn thử đổi vị với món <i1>Phở xào giòn</i1> này xem sao nhé. Bí quyết của tụi mình khi làm món phở này là trộn bánh phở với lòng đỏ trứng và bột ngô. Hai thứ nguyên liệu này sẽ giúp cho bánh phở giòm rụm mà lại có vị đậm đà và màu vàng ươm từ trứng.',
    },
    {
        "id": "10",
        "name": "Pad Thái",
        "category": "asia",
        "img": "http://culinaryfrank.com/wp-content/uploads/2019/04/culinary-frank-padthai-8-768x432.jpg",
        "favorited_amount": "74",
        description: 'Cách làm <i1>Pad Thái</i1> cũng vô cùng đơn giản. Điểm quan trọng của món này chính là nước sốt và sợi phở.<br>Thay vì dùng sợi phở tươi như trong các món phở xào ở nước ta, Pad Thái lại dùng sợi phở khô.Phở khô giúp cho nước sốt chua chua ngọt ngọt bám tốt hơn, đặc biệt là sợi phở sẽ cố độ dai nhất định, đem lại cảm giác ăn vô cùng thích thú.Sốt Pad Thái hương vị chủ đạo là vị chua của me, vị ngọt của đường thốt nốt và vị mặn của nước mắm. Tôm thường là protein được sử dụng thông dụng nhất, tuy nhiên các bạn cũng có thể dùng thịt gà, thịt bò hoặc thịt heo nhé.',
    },
    {
        "id": "11",
        "name": "Chả Tôm Thái",
        "category": "aisa",
        "img": "http://culinaryfrank.com/wp-content/uploads/2019/05/culinary-frank-thai-shrimp-cake-1.jpg",
        "favorited_amount": "60",
        description: '<i1>Chả tôm kiểu Thái</i1> thu hút người thưởng thức bởi vẻ đẹp tươi sáng bên ngoài và hương vị thơm ngon bên trong. Cái giòn rợm của bột áo ở ngoài kết hợp với vị ngọt đậm đà của tôm ở trong chắc chắn sẽ làm bạn không thể chối từ. Chả tôm giòn kiểu Thái chấm kèm sốt ớt chua ngọt chắc chắn là món ăn ngon tuyệt cho cả nhà.',
    },
    {
        "id": "12",
        "name": "Thịt kho Đông Pha",
        "category": "foreign",
        "img": "http://culinaryfrank.com/wp-content/uploads/2018/11/culinary-frank-dong-po-pork-4.jpg",
        "favorited_amount": "53",
        description: '<i1>Thịt kho Đông Pha </i1>có tên gọi bắt nguồn từ tên của nhà thơ, học giả nổi tiếng Tô Đông Pha của triều đại Bắc Tống, Trung Quốc. Ông cũng là người rất yêu thích việc nấu nướng và món thịt kho mang tên ông chính là minh chứng cho điều này.',
    },
    {
        "id": "13",
        "name": "Vietnamese Irish Coffee Recipe",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2014/03/vietnamese-irish-coffee-7w11.jpg",
        "favorited_amount": "205",
        description: 'My favourite way to drink coffee is a bastardized version of Vietnamese coffee: espresso with just a touch bit of sweetened condensed milk stirred in. I do love traditional Vietnamese coffee too, with it’s rich, deep flavour and loads of sweetened condensed milk, but in the morning, the speed of the nespresso machine wins over the slow drip, drip of metal filter every time.',
    },
    {
        "id": "14",
        "name": "Nem Nuong/Grilled Vietnamese Pork Sausage Recipe",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2017/05/nem-nuong-recipe-6944-Editw.jpg",
        "favorited_amount": "65",
        description: 'Nem nuong, or nem, which just means sausage, for short, is a staple on most Vietnamese menus. It’s a signature pink color (from food coloring) and you’ll usually see it grilled or pan-fried and served with rice or vermicelli. It comes in patties, balls, or sometimes on a skewer. Sometimes, if you’re lucky, you can order it with a ton of veggies and rice paper so you can roll up your own salad rolls.',
    },
    {
        "id": "15",
        "name": "Vietnamese Steak and Vermicelli Bowl Recipe",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2014/06/steak-bun-7w11.jpg",
        "favorited_amount": "223",
        description: 'In the summertime (okay, actually, really, all the time) I am all about the steaks. I think my steak-deprived childhood has turned me into a steak fiend. But really, it’s hard not to love steak, especially when there are so many delicious ways to eat it. One particularly delicious way is in bún, a Vietnamese bowl of grilled meat, vermicelli and dipping sauce.<br>This is by no means a traditional bowl, with the avocados and tomatoes, but it really, really works. The sweet acidity of the tomatoes goes well with the steak and the creaminess of the avocados pairs nicely with the texture of the vermicelli. Dump a boat load of fish sauce on top and you are on your way to deliciousness. ',
    },
    {
        "id": "16",
        "name": "Ốc xào sả ớt",
        "category": "viet",
        "img": "https://beptruong.edu.vn/wp-content/uploads/2018/06/mon-oc-buou-xao-sa-ot.jpg",
        "favorited_amount": "140",
        description: 'Ốc chứa nhiều chất dinh dưỡng, đặc biệt là canxi và các loại vitamin A, B1, B2…. Trong y học, ốc đồng có vị ngọt, tính hàn nên thanh nhiệt, lợi thủy, trị đái khó, giải độc tiêu nhọt, trĩ ra máu, mắt đỏ sưng tấy…. Từ xa xưa, ốc đã là nguyên liệu chế biến ra nhiều món ngon, nhất là <i1>Ốc xào sả ớt</i1> và ốc xào măng. Cùng chinh phục hai món này qua công thức nấu ăn để làm món ốc xào sả ớt và cách làm ốc xào măng dưới đây nhé!',
    },
    {
        "id": "17",
        "name": "Vietnamese Fish Tacos with Quick-Pickled Carrots and Daikon",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2015/08/vietnamese-fish-tacos-recipe-3w.jpg",
        "favorited_amount": "202",
        description: 'Sometimes it feels like everyday is Taco Tuesday around these parts. I’m not complaining though – I’ll never say no to a fluffy, soft tortilla filled with deliciousness. Especially when that deliciousness is a decidedly Vietnamese take on fish tacos. The fish here is seasoned with fish sauce, sugar, and a wee bit of turmeric for a happy yellow hue. Toss it all up with some dill, tomatoes, mint, and cilantro and you’ve got a happy mash-up of Mexican and Vietnamese flavors.',
    },
    {
        "id": "18",
        "name": "Juicy crispy pork carnitas, just like your favorite taco truck",
        "category": "foreign",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2020/08/easy-pork-carnitas-recipe-3330w.jpg",
        "favorited_amount": "64",
        description: 'I’m kind of new to the Mexican food world. I mean, I’ve been eating and enjoying Mexican food for a while now, but I definitely did not grow up eating Mexican food, other than the rare hard shell taco night. I LIVED for crunchy taco night. I thought it was the most delicious thing ever and I really loved the ritual of everyone assembling their own tacos right at the table. Now I know, real Mexicans don’t do the hard shell taco thing, and I have a lot to learn about Mexican food.',
    },
    {
        "id": "19",
        "name": "A Very Authentic Countryside Bún Bò Xả Ớt – Vietnamese Lemongrass Beef Recipe",
        "category": "viet",
        "img": "https://iamafoodblog.b-cdn.net/wp-content/uploads/2020/06/bun-bo-xa-ot-recipe-4012w.jpg",
        "favorited_amount": "172",
        description: "Bò xả ớt means beef with lemongrass and chili. It’s a favorite dish in Vietnam and increasingly famous in the rest of the world. It’s charred, smoky, lemongrassy, sweet, and slightly spicy beef, usually served as part of a vermicelli bowl or in a rice plate, or as the central protein of a salad roll party, although that’s usually more done at home. If you can find the DIY salad roll version in a restaurant, you’ve struck gold.",
    },
    {
        "id": "20",
        "name": "Pancake",
        "category": "foreign",
        "img": "https://i2.wp.com/www.eatthis.com/wp-content/uploads/2019/11/whole-grain-pancake-stack.jpg?fit=1200%2C879&ssl=1",
        "favorited_amount": "53",
        description:'Bánh <i1>Pancake</i1> còn được biết đến với tên gọi quen thuộc là bánh kếp – một món bánh khá phổ biến ở nhiều quốc gia trên thế giới. Nhờ hương vị thơm ngon mới lạ, nhiều dưỡng chất mà chỉ trong vài năm trở lại đây, khi du nhập vào Việt Nam thì bánh pancake đã được rất nhiều người ưa chuộng.',
    }
]